#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Squid Proxy HTTPS Whitelist Setup
Installs and configures Squid to whitelist a single domain.
"""
from __future__ import print_function

import argparse
import os
import shutil
import subprocess
import sys
import time

# ------------------------------------------------------------------------------
# ANSI color codes
# ------------------------------------------------------------------------------
C_RESET = "\033[0m"
C_RED = "\033[91m"
C_GREEN = "\033[92m"
C_YELLOW = "\033[93m"
C_CYAN = "\033[96m"
C_BOLD = "\033[1m"
C_DIM = "\033[2m"


# ------------------------------------------------------------------------------
# Output helpers
# ------------------------------------------------------------------------------
def banner():
    """Print ASCII banner."""
    art = r"""
    {cyan}{bold}
     ___  ___  _   _ ___ ___    ___ ___ _____  ___   _____
    / __|/ _ \| | | |_ _|   \  / __| __|_   _|/ | | | | _ \
    \__ \ (_) | |_| || || |) | \__ \ _|  | | | |_| |_| |  _/
    |___/\__\_\\___/|___|___/  |___/___| |_|  \___/___/|_|

    {reset}{dim}[ HTTPS WHITELIST PROXY CONFIGURATOR ]{reset}
    """.format(cyan=C_CYAN, bold=C_BOLD, reset=C_RESET, dim=C_DIM)
    print(art)


def info(msg):
    """Print info message."""
    print("{cyan}[*]{reset} {msg}".format(cyan=C_CYAN, reset=C_RESET, msg=msg))


def success(msg):
    """Print success message."""
    print("{green}[+]{reset} {msg}".format(green=C_GREEN, reset=C_RESET, msg=msg))


def error(msg):
    """Print error message."""
    print("{red}[-]{reset} {msg}".format(red=C_RED, reset=C_RESET, msg=msg))


def warn(msg):
    """Print warning message."""
    print("{yellow}[!]{reset} {msg}".format(yellow=C_YELLOW, reset=C_RESET, msg=msg))


def action(msg):
    """Print action message."""
    print("{cyan}[>]{reset} {msg}".format(cyan=C_CYAN, reset=C_RESET, msg=msg))


def step_delay():
    """Small delay for dramatic effect."""
    time.sleep(0.3)


# ------------------------------------------------------------------------------
# System checks
# ------------------------------------------------------------------------------
def check_root():
    """Check if running as root."""
    info("Checking privileges...")
    step_delay()
    if os.geteuid() != 0:
        error("ACCESS DENIED: Must run as root")
        error("Try: sudo python {0}".format(sys.argv[0]))
        sys.exit(1)
    success("Root access confirmed")


def check_squid_installed():
    """Check if Squid is already installed."""
    info("Scanning for existing Squid installation...")
    step_delay()
    ret = subprocess.call(
        ["which", "squid"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )
    return ret == 0


# ------------------------------------------------------------------------------
# Installation
# ------------------------------------------------------------------------------
def install_squid():
    """Install Squid proxy via apt-get."""
    action("Updating package lists...")
    step_delay()
    ret = subprocess.call(["apt-get", "update", "-qq"])
    if ret != 0:
        error("Failed to update package lists")
        sys.exit(1)
    success("Package lists updated")

    action("Installing squid package...")
    step_delay()
    ret = subprocess.call(["apt-get", "install", "-y", "-qq", "squid"])
    if ret != 0:
        error("Failed to install Squid")
        sys.exit(1)
    success("Squid package installed")


# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------
def generate_config(domain, port):
    """Generate Squid configuration for domain whitelisting."""
    # Ensure domain starts with a dot for wildcard matching
    if not domain.startswith("."):
        domain = "." + domain

    config = """#
# SQUID PROXY - WHITELIST CONFIGURATION
# Generated by setup_squid_whitelist.py
# Whitelisted domain: {domain}
# Listen port: {port}
#

# ACL definitions
acl localnet src 10.0.0.0/8
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl localnet src fc00::/7
acl localnet src fe80::/10

acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT

# Whitelist domain ACL
acl whitelist_domain dstdomain {domain}

# Security rules - deny unsafe ports
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports

# Allow localhost
http_access allow localhost manager
http_access deny manager

# Allow whitelisted domain only (HTTP and HTTPS)
http_access allow whitelist_domain

# Deny everything else
http_access deny all

# Squid listening port
http_port {port}

# Logging
access_log /var/log/squid/access.log squid
cache_log /var/log/squid/cache.log

# Cache directory
cache_dir ufs /var/spool/squid 100 16 256

# Refresh patterns
refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern -i (/cgi-bin/|\\?) 0     0%      0
refresh_pattern .               0       20%     4320

# PID file
pid_filename /var/run/squid.pid

# Visible hostname
visible_hostname squid-whitelist-proxy
""".format(domain=domain, port=port)

    return config


def backup_config():
    """Backup existing Squid configuration."""
    squid_conf = "/etc/squid/squid.conf"
    backup_path = "/etc/squid/squid.conf.bak"

    if os.path.exists(squid_conf):
        info("Backing up existing configuration...")
        step_delay()
        try:
            shutil.copy2(squid_conf, backup_path)
            success("Backup saved to {0}".format(backup_path))
        except IOError as e:
            warn("Could not backup config: {0}".format(e))


def write_config(config, script_dir):
    """Write configuration to both /etc/squid and script directory."""
    squid_conf = "/etc/squid/squid.conf"
    local_conf = os.path.join(script_dir, "squid.conf")

    # Write to /etc/squid/squid.conf
    action("Writing configuration to {0}...".format(squid_conf))
    step_delay()
    try:
        with open(squid_conf, "w") as f:
            f.write(config)
        success("Configuration written to {0}".format(squid_conf))
    except IOError as e:
        error("Failed to write config: {0}".format(e))
        sys.exit(1)

    # Write local copy
    action("Saving local copy to {0}...".format(local_conf))
    step_delay()
    try:
        with open(local_conf, "w") as f:
            f.write(config)
        success("Local copy saved to {0}".format(local_conf))
    except IOError as e:
        warn("Could not save local copy: {0}".format(e))


# ------------------------------------------------------------------------------
# Service management
# ------------------------------------------------------------------------------
def restart_squid():
    """Restart Squid service."""
    action("Restarting Squid service...")
    step_delay()
    ret = subprocess.call(["systemctl", "restart", "squid"])
    if ret != 0:
        error("Failed to restart Squid")
        sys.exit(1)
    success("Squid service restarted")


def verify_squid():
    """Verify Squid is running."""
    info("Verifying Squid status...")
    step_delay()
    ret = subprocess.call(
        ["systemctl", "is-active", "--quiet", "squid"]
    )
    if ret != 0:
        error("Squid is not running")
        error("Check logs: journalctl -u squid")
        sys.exit(1)
    success("Squid is active and running")


def enable_squid():
    """Enable Squid to start on boot."""
    action("Enabling Squid on system startup...")
    step_delay()
    ret = subprocess.call(["systemctl", "enable", "squid"], stderr=subprocess.PIPE)
    if ret == 0:
        success("Squid enabled on boot")
    else:
        warn("Could not enable Squid on boot")


# ------------------------------------------------------------------------------
# Main
# ------------------------------------------------------------------------------
def print_summary(domain, port):
    """Print configuration summary."""
    print("")
    print("{bold}{green}".format(bold=C_BOLD, green=C_GREEN) + "=" * 60 + C_RESET)
    print("{bold}{green}  CONFIGURATION COMPLETE{reset}".format(
        bold=C_BOLD, green=C_GREEN, reset=C_RESET))
    print("{bold}{green}".format(bold=C_BOLD, green=C_GREEN) + "=" * 60 + C_RESET)
    print("")
    print("  {cyan}Proxy Address:{reset}  localhost:{port}".format(
        cyan=C_CYAN, reset=C_RESET, port=port))
    print("  {cyan}Whitelisted:{reset}    *{domain}".format(
        cyan=C_CYAN, reset=C_RESET, domain=domain))
    print("")
    print("  {dim}Test commands:{reset}".format(dim=C_DIM, reset=C_RESET))
    print("  {green}curl -x http://localhost:{port} https://www{domain}{reset}".format(
        green=C_GREEN, reset=C_RESET, port=port, domain=domain))
    print("  {red}curl -x http://localhost:{port} https://example.com  # blocked{reset}".format(
        red=C_RED, reset=C_RESET, port=port))
    print("")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Install and configure Squid proxy with domain whitelist",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  sudo python {0} --domain .google.com --port 8080
  sudo python {0} -d .github.com -p 3128
        """.format(sys.argv[0])
    )
    parser.add_argument(
        "-d", "--domain",
        default=".google.com",
        help="Domain to whitelist (default: .google.com)"
    )
    parser.add_argument(
        "-p", "--port",
        type=int,
        default=8080,
        help="Proxy listen port (default: 8080)"
    )
    args = parser.parse_args()

    # Get script directory for local config copy
    script_dir = os.path.dirname(os.path.abspath(__file__))

    # Ensure domain format
    domain = args.domain
    if not domain.startswith("."):
        domain = "." + domain

    # Run setup
    banner()
    print("")

    info("Target domain: *{0}".format(domain))
    info("Listen port: {0}".format(args.port))
    print("")

    check_root()
    print("")

    if check_squid_installed():
        success("Squid already installed")
    else:
        warn("Squid not found")
        install_squid()
    print("")

    backup_config()
    config = generate_config(domain, args.port)
    write_config(config, script_dir)
    print("")

    restart_squid()
    enable_squid()
    verify_squid()

    print_summary(domain, args.port)


if __name__ == "__main__":
    main()
